//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insight.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL_NAME,SSAN,GRADE,RECORD_STATUS,ASSIGNED_PAS,ASSIGNED_PAS_CLEARTEXT,OFFICE_SYMBOL,DUTY_TITLE,DUTY_START_DATE,DOR,DAFSC,CAFSC,PAFSC,2AFSC,3AFSC,4AFSC,DATE_ARRIVED_STATION,DUTY_PHONE,TAFMSD,DOE,DOS,ETS,DATE_OF_BIRTH,HOME_ADDRESS,HOME_CITY,HOME_STATE,HOME_ZIP_CODE,SUPV_NAME,GRADE_PERM_PROJ,UIF_CODE,UIF_DISPOSITION_DATE,PROJ_EVAL_CLOSE_DATE,MARITAL_STATUS,RNLTD,GAINING_PAS,GAINING_PAS_CLEARTEXT,LAST_EVAL_RATING,LAST_EVAL_CLOSE_DATE,PERF_INDICATOR,SPOUSE_SSAN,SUPV_BEGIN_DATE,REENL_ELIG_STATUS,HOME_PHONE_NUMBE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AlphaRosterExpectedSchema {
            get {
                return ResourceManager.GetString("AlphaRosterExpectedSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortName,PEX Designation.
        /// </summary>
        internal static string PEXExpectedSchema {
            get {
                return ResourceManager.GetString("PEXExpectedSchema", resourceCulture);
            }
        }
    }
}
